### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by Fleshgrinder** [boyter/scc#143]
Would it be possible that we get an official Docker image? You could host it [on GitHub](https://github.com/features/packages) like the pre-compiled binaries. Having a Docker image would simplify the usage with automation (e.g. CI).

**Comment by boyter** [comment]
Yep a docker image sounds like a good idea. I will have a look to see what this involves.

**Comment by Potherca** [comment]
Based on the work of [gitlab-ci-utils/docker-scc](https://gitlab.com/gitlab-ci-utils/docker-scc) (MIT License), I came up with this:

```Dockerfile
# hadolint ignore=DL3007
FROM golang:latest as scc-get

ENV GOOS=linux \
GOARCH=amd64 \
CGO_ENABLED=0

ARG VERSION=v3.0.0
RUN git clone --branch $VERSION --depth 1 https://github.com/boyter/scc
WORKDIR /go/scc
RUN go build -ldflags="-s -w"

FROM scratch
COPY --from=scc-get /go/scc/scc /scc
ENTRYPOINT ["/scc"]
```

which is basically an empty docker image with only the `scc` binary in it.

I guess the majority of the work that needs to be doen for this issue is setting up all of the right GitHub Action, correct?

**Comment by boyter** [comment]
> setting up all of the right GitHub Action

That would be it as far as I can see. 

I really need to block out some time to get all of this done.
