### ISSUE TITLE
Count comments at the end of code lines

### ISSUE THREAD

**Issue by r-barnes** [boyter/scc#167]
Is there a way to count comments at the end of lines of code?

For instance, I see 2 lines in this snippet which contain comments, but scc only sees one.
```
#include <iostream>

//hi
int main(){
  test;
  test; //hi
}
```

**Comment by boyter** [comment]
So not out of the box with the way scc works, IE from the final binary. However you can hook into the code yourself to achieve this.

https://github.com/boyter/scc#api-support

Have a look at the above. You can use the code to register your callback telling you what the state was at the end of each line. The catch being it currently squashes this down to a generic blank, code or comment indicator, but we could expand this out allowing you to determine the exact type allowing you to see if if a line finishes in a state you are interested in such as,

```
SMulticommentCode  int64 = 6 // Indicates multi comment after code
```

Whats the use case you are after here? Trying to count the number of lines that contain comments or some such? Because I am not opposed to adding an option where you can specify to get the count of everything even if it means those counts will be higher than the number of lines as a single line can me multiple things.

**Comment by boyter** [comment]
Closing due to no response.
