### ISSUE TITLE
Disable --by-file for CSV output

### ISSUE THREAD

**Issue by rohitn** [boyter/scc#203]
CSV output forces `--by-file` and there does not seem to be a way to disable it. Other output formats do not do this. Why is CSV special? Why not let the user choose by explicitly specifying `--by-file` if needed? Thanks.

**Comment by boyter** [comment]
The main reason for this was I felt that if you were exporting to CSV it was because you are likely to want to run your own aggregations. Hence override.... SQL format does the same thing (although this is done to ensure it is compatible with cloc more than anything else).

I guess I see CSV and SQL occupying the same sort of niche output. Happy to be convinced otherwise though. 

What use case are you anticipating where this would be desirable?

**Comment by rohitn** [comment]
Hi Ben,

Thank you for the prompt response. 

My use case is quite simple. There are several repositories against which I need to run scc for counts by language and integrate it into a build process. Each repository needs different scc option settings. After verifying all the settings I tried to generate CSV of the same output and was surprised that it was grouped by language and file and that the total row is missing. I would need an extra step to import the CSV into Excel or a DB, aggregate, and export as part of automating the process. There is no `--not-by-file` option to turn it off. Changing the behavior would be backward incompatible, not a good option.

I need this change soon, so I have forked the repo and started adding a `csv-table` format using `func toHtmlTable` as an example.

**Comment by boyter** [comment]
I have no problem with making incompatible version changes :) The next version is already going to be 3.0.0 so putting this in isn't a huge issue from my perspective.

**Comment by boyter** [comment]
@rohitn This is sitting on a branch currently, but I have an example of the CSV below. Its a breaking change so `scc -f csv` is now by default the summary, but you can get the old logic with `scc -f csv --by-file`

[summary.txt](https://github.com/boyter/scc/files/6026242/summary.txt)
[by_file.txt](https://github.com/boyter/scc/files/6026241/by_file.txt)
