### ISSUE TITLE
file without an extension count as an extension

### ISSUE THREAD

**Issue by ivoszz** [boyter/scc#21]
Hi,
I just `go get` scc and try it to count on my project. I was surprised with line:
```
Robot Framework              1     54580    53988         0      592          0
```

Actually I have binary with the name `robot` and scc counts this binary as a `.robot` extension. When I renamed my binary to `robot1`, the line disappeared. Your program looks fine, but you should count only on extensions, not on names which duplicate extension name.

P.S.: Counting `adoc` (asciidoc) files is almost same like counting markdown files. We use them for documentation. It is pity `adoc` is not in the default configuration.

**Comment by boyter** [comment]
So the problem with not counting the extension is that `scc` tries to count files like `Dockerfile` or `.gitignore` which means it does also look at the filename as a whole thing. I will have a think about this though. One way I can think of resolving it is modifying the database so that it is aware when it should attempt this or not.

As for adding `adoc` its pretty simple. Whats the extension of them? Guessing `adoc` but not 100% sure on that. If that is so all you would need to do is add the following,

```
 "asciidoc": {
    "line_comment": [],
    "complexitychecks": [],
    "extensions": [
      "adoc"
    ],
    "multi_line": [],
    "quotes": []
  }
```

into `languages.json` then run `go generate && go install` and it will recognize the language.

Let me know if `adoc` is the correct extension and I will add it into `scc` proper, or if you prefer submit a PR and I will include it into the next release.

**Comment by boyter** [comment]
Had a quick look and AsciiDoc was indeed very easy to add. Now sitting in master.

**Comment by boyter** [comment]
Hi @ivoszz could you try pulling the latest from master and installing it? Both AsciiDoc will be included and counted and the robot file should now be identified as being binary and excluded from all counts.

Let me know how that works out for you.

**Comment by ivoszz** [comment]
Hi @boyter, thanks for your super quick response. I checked your fix and everything looks fine.
