### ISSUE TITLE
Release include linux ARM platform

### ISSUE THREAD

**Issue by AnonymousArthur** [boyter/scc#211]
ARM Linux platform coding/CICD need is raising, maybe we could have an ARM release version?

**Comment by boyter** [comment]
100% planned. Waiting on the next Go release so I can include the new Apple Silicon as well.

What I do need is a test ARM system in order to try it out though, its the only reason I have been hesitant to do so before. Might have to try one of the AWS Graviton instances to ensure it works as expected.

**Comment by boyter** [comment]
Confirmed this works as expected on Apple M1 silicon. Probably good enough to push a general ARM release out then.

**Comment by AnonymousArthur** [comment]
Thank you so much.

**Comment by boyter** [comment]
Note this is 100% dependent on the next release of Go 1.16 which has Apple M1 support. So will need to wait till then :)

However I can confirm it works under the beta so moving to done, but not closing till then.

**Comment by boyter** [comment]
Can confirm this works fine on Go 1.16. Closing out and ARM Apple and Linux will be in the next release.
