### ISSUE TITLE
Request to calculate method/class metrics?

### ISSUE THREAD

**Issue by AZHenley** [boyter/scc#22]
It would be great to have stats on average method/class length and total number of methods/classes.

**Comment by boyter** [comment]
So I don't know of a way to do that currently because the files are not AST parsed.

It may be possible to add in method markers, and push pop the state in order to know when the method ends, but that would be rather complex. I will have a think on it but I doubt its going to happen unless someone else submits it as a PR as its more than I would want to implement myself.

That said, if you are able to determine them you could reuse all the code and feed it though to calculate it.

**Comment by boyter** [comment]
So having thought about this its more work that I am willing to commit to. I think you would be better off finding another tool that is specific per language to do this. If you are able to make an elegant PR that includes this I will be happy to merge it in.
