### ISSUE TITLE
Is there a "DIFF" type feature?

### ISSUE THREAD

**Issue by fignutz** [boyter/scc#239]
Maybe it's painfully obvious from the README documentation/`--help` output, but I can't ascertain if `SCC` has a **DIFF** feature. Specifically, a feature that analyzes source files between baselines to determine the counts for logical source lines of code(SLOC) added, deleted, modified, or unmodified. If this feature exist, what switch (or combination of switches) need to be used?

**Comment by boyter** [comment]
So out of the box, no. However I have done this myself. See the attached where I used scc to create PR counts.

I did this by comparing the results from 2 commits, but you could do it per file or language if you needed such a breakdown. I think this is probably much easier with the SQL output that scc now has as you could append the output together and then compare with some SQL.

I don't think this is something I am likely to add in `scc` itself, unless someone comes up with a really good reason for it as its starting to get a little more complex than I would like to deal with. Happy to be convinced otherwise though.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/612151/110720512-cb0d8980-8262-11eb-9649-6f11eecf29f4.png">

**Comment by fignutz** [comment]
Sweet, thanks so much for your example on this. There is technically a need for DIFF to be inline, ideally, but I don't have a good enough argument to convince you that wouldn't involve making a passion plea for SLOC-based costing and bidding...which is something I don't completely endorse myself. In any event; thanks!

**Comment by boyter** [comment]
Thanks for being so understanding. As I said, being able to do it though SQL should work for the most part.
