### ISSUE TITLE
How to show the line number of the type [Code/Blank] when it scans a file

### ISSUE THREAD

**Issue by xiao623** [boyter/scc#242]
I know that it will scans every line of each file and detects the type of line that is.
But I want to know the line number of blank or code.

For example,

a.c
```
Line number   Content
1 // blala
2
3  if ( a == b) {
...
```

Expected Result
The line numbers of Blank : 2
The line numbers of Code : 3
The line numbers of Comment : 1

**Comment by boyter** [comment]
Assuming you want to do this in code see https://github.com/boyter/scc#api-support

Otherwise you can use the verbose output which will tell you this `scc -v file`

It will print out the end state of every line, however not in the format it is. I would suggest using the API support which will allow you to inject callbacks giving you this information and then you can get whatever output format you want.

**Comment by xiao623** [comment]
It seems that `scc -t file` would help.

**Comment by boyter** [comment]
Ah I see what you mean. Yes if you just want per line, that should do it :)
