### ISSUE TITLE
Can't find --files option

### ISSUE THREAD

**Issue by CeleritasCelery** [boyter/scc#265]
**Describe the bug**
I installed scc from the snap package (which is version 3.0.0). I was looking through [this](https://boyter.org/posts/why-count-lines-of-code/) blog post about how to use it, but several of the options used in the blog post don't exist in the latest version. I don't see them in the [readme](https://github.com/boyter/scc#usage) either. These include `--files`, `--pbl`, `-wl`, and `-co`.

**To Reproduce**

1. `sudo snap install scc`
2. `scc --files`
3. observe `Error: unknown flag: --files`

**Expected behavior**
Displays lines per file as shown in the blog post. Instead I see 

**Desktop**
 - OS: Linux
 - Version: 3.0.0

**Comment by boyter** [comment]
Sorry about that, the post is rather out of date. I think its from the 1.0.0 release days of scc. I forget the exact reason but it was changed to `--by-file`. I think because it's closer to some existing tools in the space? Anyway you can swap `--file` for `--by-file` and everything you would expect should work as you expect.

As for the other options, which were changed for various other reasons, mostly to improve discoverability 

`--pbl` is now `--exclude-dir`
`--wl` is now `--include-ext` or `-I`
`--co` is now `--no-cocomo`

I should probably go back and fix that post to address these. Once again I do apologise for the confusion.

**Comment by CeleritasCelery** [comment]
Didn't realize the post was out of date. Just saw it yesterday on HN. Thanks for the clarification.

**Comment by boyter** [comment]
Oh I didn't even know it was on HN. Usually I pick up on that. 

Glad its all sorted out for you.
