### ISSUE TITLE
Discuss about the bloom filter use

### ISSUE THREAD

**Issue by foxdd** [boyter/scc#276]
**Describe the bug**
Do we really need bloom filter for all the situations?

**To Reproduce**

1. The advantage of bloom filter is to save much memory space when we need to figure out the existence of a huge number of values. While in SCC situation, we only need to deal with 255 ASCII characters. 
2. For most languages and no complexity process, current bloom filter method can perfectly ensure accuracy and velocity,  which can be regarded as the best way. While for some languages (golang for example, with quotes of \`), the bloom filter is not the best choice. This is for the reason that the bloom hash value of ` can be very similar as some other letters, which will lead to misjudgement.

**Test Result**
We embedded a counter into the shouldProcess function of worker.go. The counter will atomic add 1 whenever the function returns true so that we can calculate how many times in total the following logic is processed. So we tested a typical golang project for time consuming and processing count in bloom filter and no bloom filter(simple hash map filter) situations with the augment no-complexity of false.

```
bloom filter:
process count: 2354969
time consume in millisecond: 297

no-bloom-filter:
process count: 2079763
time consuming in millisecond: 273
```

Use hyperfine to test with command `'hyperfine -r 50 "scc --no-complexity=false --no-bloom-filter=false D:/go_test" "scc --no-complexity=false --no-bloom-filter=true D:/go_test"'`
we get the result:
```
no-bloom-filter=false   Time (mean ± σ):     214.4 ms ±  43.4 ms    [User: 2.9 ms, System: 6.0 ms]
no-bloom-filter=true    Time (mean ± σ):     199.7 ms ±  10.4 ms    [User: 1.8 ms, System: 9.2 ms]
```

`'scc --no-complexity=false --no-bloom-filter=true D:/go_test' ran
    1.07 ± 0.22 times faster than 'scc --no-complexity=false --no-bloom-filter=false D:/go_test'`

**Conclusion:**
So we think we may first provide a augment for user to choose if they want to use bloom filter. Later on we can atomatically configure scc tool regarding which input parameter and language is being processe

see pr #277

**Comment by dbaggerman** [comment]
Hi @foxdd,

I _think_ I considered using this type of map lookup when I was implementing the bloom filer, but I can't remember why I ended up going with the current implementation instead. It doesn't hurt to revisit the idea.

First, you could simplify your code a little by using `[256]bool` instead of `[256]uint64`, since the `uint64` is only ever going to be `0` or `1` anyway.

Second, the inner loop of `scc` is very performance sensitive, and adding conditions there isn't free. We need to compare to the current master version, not just with `--no-bloom-filter` true/false.

My test (against github.com/golang/go) found your branch to be slower than `master` regardless of the `--no-bloom-filter` setting.

```
Benchmark #1: ./scc-master --no-complexity=false golang/go
  Time (mean ± σ):     102.3 ms ±   4.6 ms    [User: 810.2 ms, System: 210.7 ms]
  Range (min … max):    94.9 ms … 115.9 ms    50 runs

Benchmark #2: ./scc-pr277 --no-complexity=false --no-bloom-filter=false golang/go
  Time (mean ± σ):     443.6 ms ±  26.8 ms    [User: 5.682 s, System: 0.183 s]
  Range (min … max):   413.7 ms … 515.0 ms    50 runs

Benchmark #3: ./scc-pr277 --no-complexity=false --no-bloom-filter=true golang/go
  Time (mean ± σ):     437.9 ms ±  22.8 ms    [User: 5.648 s, System: 0.177 s]
  Range (min … max):   410.8 ms … 488.2 ms    50 runs

Summary
  './scc-master --no-complexity=false golang/go' ran
    4.28 ± 0.30 times faster than './scc-pr277 --no-complexity=false --no-bloom-filter=true golang/go'
    4.34 ± 0.33 times faster than './scc-pr277 --no-complexity=false --no-bloom-filter=false golang/go'
```

You could try having your implementation replace the current filter entirely and see what the numbers look like. If you want to keep the toggle, you could also try putting both filters behind an `interface` - which would pull the condition out of the inner loop.

**Comment by foxdd** [comment]
@dbaggerman hihi, thanks a lot for your introduce about your work on the bloom filter accelaration. I will try to optimize my pull request by your advice. 
However, Regardless of performance reduction made by the new code in the inner loop of `scc`, the simple map lookup does obviously reduce the invalid executions of the code behind `shouldProcess` function, which i think is potential for performance enhancement. Do you have any ideas about how to make `scc` tool decide which method to use by itself?
Perhaps we can do more test, and collect which token of all the languages in `language.json` will lead to misjudgement for bloom filter and which not. After that, we can set a new property in the `langugage.json` to figure out using bloom filter or not when processing the language features.
Thanks for your rapid response again~~

**Comment by dbaggerman** [comment]
@foxdd, I think the problem with the current implementation is the condition inside `shouldProcess`. Since `shouldProcess` gets called for every byte of every file, it's having to ask "should I filter this byte with or without bloom filter?" thousands of times.

One way to solve that is to only have one option, if your implementation is fast enough to replace the bloom filter everywhere. The other suggestion was to try using an `interface` - that way you only need to decide which option to use once, rather than on every byte.

I'm imagining something like:
```go
interface ByteFilter {
  shouldProcess(byte) bool
}
```

Then you can create a `BloomFilter` implementation and a `BloomMap` implementation of the interface. If you add a `ByteFilter` field to `LanguageFeatures`, you can decide which to use in `processLanguageFeature`. Then `StateCode.Process` would be able to call `lang.byteFilter.shouldProcess()` without any overhead of checking flags for every byte.

**Comment by foxdd** [comment]
@dbaggerman ok, i will first recode by this

**Comment by foxdd** [comment]
@dbaggerman

**Comment by foxdd** [comment]
@dbaggerman 
i have made ByteFilter interface for these two filter type. Currently, it still only depends on the input parameter no-bloom filter, of which the default value is false. In the following test, more factors need to be put into consideration for the choice of the filter type, for example, as you sayed before, eache language with different Complexity/LineComment/MultiLine/Quotes tokens, and no-complexity parameter

**Comment by foxdd** [comment]
@dbaggerman i think you can re-test the performance on the code of same branch with differenct no-bloom-filter input

**Comment by dbaggerman** [comment]
```
Benchmark #1: ./scc-master --no-complexity=false golang/go
  Time (mean ± σ):     100.4 ms ±   4.4 ms    [User: 807.0 ms, System: 208.1 ms]
  Range (min … max):    94.0 ms … 113.2 ms    50 runs

Benchmark #2: ./scc-pr277-orig --no-complexity=false --no-bloom-filter=false golang/go
  Time (mean ± σ):     437.0 ms ±  24.5 ms    [User: 5.687 s, System: 0.176 s]
  Range (min … max):   412.7 ms … 489.3 ms    50 runs

Benchmark #3: ./scc-pr277-orig --no-complexity=false --no-bloom-filter=true golang/go
  Time (mean ± σ):     441.9 ms ±  25.4 ms    [User: 5.650 s, System: 0.179 s]
  Range (min … max):   409.2 ms … 482.1 ms    50 runs

Benchmark #4: ./scc-pr277-iface --no-complexity=false --no-bloom-filter=false golang/go
  Time (mean ± σ):     118.2 ms ±   4.3 ms    [User: 1.104 s, System: 0.198 s]
  Range (min … max):   111.7 ms … 133.7 ms    50 runs

Benchmark #5: ./scc-pr277-iface --no-complexity=false --no-bloom-filter=true golang/go
  Time (mean ± σ):     150.8 ms ±   3.2 ms    [User: 1.645 s, System: 0.188 s]
  Range (min … max):   145.5 ms … 165.3 ms    50 runs

Summary
  './scc-master --no-complexity=false golang/go' ran
    1.18 ± 0.07 times faster than './scc-pr277-iface --no-complexity=false --no-bloom-filter=false golang/go'
    1.50 ± 0.07 times faster than './scc-pr277-iface --no-complexity=false --no-bloom-filter=true golang/go'
    4.35 ± 0.31 times faster than './scc-pr277-orig --no-complexity=false --no-bloom-filter=false golang/go'
    4.40 ± 0.32 times faster than './scc-pr277-orig --no-complexity=false --no-bloom-filter=true golang/go'
```

The `interface` variation is a big improvement on your original, and much closer to the current performance - but still a little slower overall. We can also see that in this variation, `--no-bloom-filter=false` performs better after this change than `--no-bloom-filter=true`.

Some of the slowdown is probably still related to needing to dereference the function through the interface pointer, and having two implementations side-by-side might not be viable for this part of the code. If you want to keep working on it, see if you can get the `BloomMap` implementation to work as well as the existing `BloomFilter` using the `interface` model.

**Comment by boyter** [comment]
I have had to revert most of the updated bloom filter state. This was due to it breaking all of the tests and wanting to eventually get a new release out.

Just updating in here so people are aware what's going on. At this point the mainline is building with all tests passing again which is a good place to be.
