### ISSUE TITLE
SubFolder has higher estimated cost than parent folder.

### ISSUE THREAD

**Issue by Kuinox** [boyter/scc#331]
**Describe the bug**
On my repo (https://github.com/signature-opensource/CK-MQTT/), the Folder "CodeCakeBuilder" shows `Estimated Cost to Develop (organic) $277,349` the whole repo show a cost of `$123,699`.

**To Reproduce**

1. clone my repo https://github.com/signature-opensource/CK-MQTT/
2. Run `scc` in it
3. Then run `scc CodeCakeBuilder`

**Expected behavior**
The cost of a subdirectory should always be smaller than the parent directory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.0.0

**Comment by boyter** [comment]
Looking at this, it looks like its due to .gitgnore in the root.

https://github.com/signature-opensource/CK-MQTT/blob/develop/.gitignore#L253

What happens is when you provide the folder, scc assumes you want to run from that directory, and ignores where you currently are running it, hence misses the gitignore. The reason for this is you may end up running scc from your home directory at some other path. For example

```
$ pwd
/user/boyter/

$ scc /tmp/linux/sub
```

Which is valid. Something I have considered adding which I put some other tools is the ability to ask it to walk backwards looking for a .git folder indicating the root, and then pull the gitignore from there which I think would resolve this, however the out of the box functionality unconfigured is unlikely to support this.

**Comment by Kuinox** [comment]
Oh my bad, I didn't see the added 7k lines of JSON, I glanced only at the C# line count.
Sorry :D 
I think the feature you are talking about is #291 right ?
I'll close this issue then

**Comment by boyter** [comment]
Yeah gitignores are the focus of this release... or will be once I finish off all the other things I need to get done. I started work there but need to pick it back up. It comes down to adding glob support.

If someone wants to help with this it would allow me to push the release faster, but as it is its in progress.

Thanks for responding so quickly. Hope to have this all resolved soon.

**Comment by Kuinox** [comment]
Sorry, but I don't know golang at all, good luck :p
