### ISSUE TITLE
Support .astro files

### ISSUE THREAD

**Issue by lloydjatkinson** [boyter/scc#373]
`.astro` files are similar to `.vue` files in that the file contains more than one language.

They contain TypeScript in the top section and TSX in the bottom section. [Astro component documentation.](https://docs.astro.build/en/core-concepts/astro-components/)

```astro
---
import { foo, bar } from 'something';

const baz = foo(42);
---
<div>
    {bar(baz)}
</div>
```

How would this be counted, and how is it counted for Vue files? Would it be represented as "N number of lines of Astro" or would it be "N lines of Typescript, X lines of TSX"? Or would it actually be both?

**Comment by boyter** [comment]
Mixed types like this are one of the problematic things inside scc at the moment.

I am considering building out a way to support this, but I think it might be better to go to dedicated code paths for these cases on a per language basis. I want to do this anyway for some because I think there are some performance gains to be made and you can catch some of the edge cases.

Something to consider anyway.

For the above it would count it based on whatever rules would be defined. If you can define both of the language rules into a single group though, and they don't overlap in theory it should work as you would expect.

**Comment by boyter** [comment]
@meoyawn that's one workaround approach, although it does not totally address the issue annoyingly.

**Comment by meoyawn** [comment]
yeah but there's no difference between these 3 frameworks: Vue, Svelte, Astro. They all contain 3 languages in one file.

HTML started it first though with `<script>` and `<style>` 😂
