### ISSUE TITLE
Why CUDA files are not supported?

### ISSUE THREAD

**Issue by galinart** [boyter/scc#406]
OS: Windows

```
scc.exe --version
scc version 3.1.0

scc.exe --no-gitignore kernel.cu

───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
Total                        0         0        0         0        0          0
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $0
Estimated Schedule Effort (organic) 0.00 months
Estimated People Required 1 Grandparent
───────────────────────────────────────────────────────────────────────────────
Processed 0 bytes, 0.000 megabytes (SI)
───────────────────────────────────────────────────────────────────────────────
```

**Comment by boyter** [comment]
Ultimately because I have never worked with CUDA and forgot about it.

Do you know of a decent language definition for it? My very basic understanding is that its C/C++ code with a different extension? 

I want to know what extensions we expect and what to put for the complexity checks. You can see the C example linked here https://github.com/boyter/scc/blob/master/languages.json#L876 which gives an idea of what we need for this. With those, its a pretty easy to add it in.

**Comment by boyter** [comment]
Ultimately because I have never worked with CUDA and forgot about it.

Do you know of a decent language definition for it? My very basic understanding is that its C/C++ code with a different extension? 

I want to know what extensions we expect and what to put for the complexity checks. You can see the C example linked here https://github.com/boyter/scc/blob/master/languages.json#L876 which gives an idea of what we need for this. With those, its a pretty easy to add it in.

**Comment by boyter** [comment]
Added in 0f4608964fc5d2101ba0b9f2c6b6aff738e8e1d9
