### ISSUE TITLE
go install github.com/boyter/scc/v3@latest isn't working since v3.4

### ISSUE THREAD

**Issue by PhilKrau** [boyter/scc#532]
Hey, I'm using scc inside a gitlab ci/cd-pipeline and all my pipelines are failing since the command ```go install github.com/boyter/scc/v3@latest``` isn't working anymore. Up until version 3.3.5 everything ran fine, now I get the following errors:
``` 
/go/pkg/mod/github.com/boyter/scc/v3@v3.4.0/processor/detector.go:6:2: package cmp is not in GOROOT (/opt/bitnami/go/src/cmp)
/go/pkg/mod/github.com/boyter/scc/v3@v3.4.0/processor/bloom.go:3:8: package math/rand/v2 is not in GOROOT (/opt/bitnami/go/src/math/rand/v2)
/go/pkg/mod/github.com/boyter/scc/v3@v3.4.0/processor/detector.go:9:2: package slices is not in GOROOT (/opt/bitnami/go/src/slices)
```
I would appreciate any kind of help since I'm not too versed in Go.
I'm using Ubuntu 22.04 and go1.18.1 linux/amd64.
Thanks in advance for any help

**Comment by boyter** [comment]
Version 3.3.5 was updated to use Go 1.22 since the version it was on at the time was due to be EOL. 

All you would need do is update your Go version 1.22 or later (1.23 being the latest at the moment). 

I will be updating it every now and then simply to ensure it gets the latest security patches, features and performance improvements. For the future checking https://github.com/boyter/scc/blob/master/go.mod will let you know what version you need to be building from.

**Comment by PhilKrau** [comment]
Managed to fix the issue, thank you very much !

**Comment by boyter** [comment]
You are welcome!
