### ISSUE TITLE
Blanks are not counted correctly in Java

### ISSUE THREAD

**Issue by ptupitsyn** [boyter/scc#73]
**Describe the bug**
In some cases blank lines are not counted correctly in Java files.
I've simplified the example somewhat, but could not pinpoint problematic lines.

**To Reproduce**

1. Download file [AbstractSACParser.zip](https://github.com/boyter/scc/files/3137601/AbstractSACParser.zip)
2. Extract
3. Scc

**Expected behavior**
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines     Code  Comments   Blanks Complexity
───────────────────────────────────────────────────────────────────────────────
Java                         1       139      103        16        20          8
```

**Actual behavior**
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines     Code  Comments   Blanks Complexity
───────────────────────────────────────────────────────────────────────────────
Java                         1       139      119        15        5          8
```

**Desktop**
 - Windows 10

**Comment by boyter** [comment]
Does not appear to be related to #72 as the file is UTF-8 encoded.

**Comment by boyter** [comment]
Issue is the following line,

```
if (c == '\\' || (c == '\"')) {
```

The " is being picked up as the start of a string which is throwing out the count. Because `scc` counts blank lines as being code if inside a string unlike tokei this is why the count is incorrect.

In this case we could check for \ before the string since this should only occur inside a char. However not all languages work like that. I think this is acceptable for the moment as a quick fix though and to create a new issue to evaluate how this works in other languages. It should work for most of the common languages though which is a good short term win.

**Comment by boyter** [comment]
Fix for this case exists on branch https://github.com/boyter/scc/pull/75

**Comment by boyter** [comment]
Merged into master.

This will still need work to make it more flexible, so no release till that is done in https://github.com/boyter/scc/pull/76

That said closing down because if you build from master its all fine now and will make it into the next release.
