### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by dataf3l** [boyter/scc#91]
Hi guys, thank you for building the project, i really enjoyed it.

Here are some ideas/suggestions.

1. Angular projects put all their logic in html files, but the estimated cost is zero, perhaps if one finds ng-app or ng-if (or whatever the Angular kids are doing these days) then it should be possible to add complexity to the mix, I think the problem is that when code is hiding inside html files, as is often the case with JS, then the cost counter under-estimates the cost, but the opposite is also true,
when the javascript files have declarative structures, like JSX, or React-looking things, then it is possible the tool considers these as "code" when in reality it is merely "layout" and may over-estimate the cost.

Is there something that can be done about this?
detecting html or xml inside js and starting a react-mode?

2. How come the cost is always so high? I know estimating isn't perfect, but did it *really* take 4 people, 11 months, and 1/5 million dollars to build this particular tool? (maybe even WAY more considering salaries might be *very* underestimated, considering the talents of the SCC team?

is it over estimated?
under-estimated?

3. Should there be a link explaining the numbers and how they were calculated
simply, so that when the managers see the numbers they don't run away afraid?

4. Can the tool add some default ignore folders like vendor in php and node_modules?

5. Can mini-fied code be detected and omitted when a flag is present? (mostly libraries, not written by the code authors, or build artifacts)

6. How should things like md, txt and html be calculated for cost?, particularly in the presence of generators?
7. Can there be a estimate for cost of maintenance?

8. should cost consider complexity of programming languages? it's not the same to have 10 lines of css than 10 lines of ML code than 10 lines of template meta-programming multi-threaded hardened c++ server code, or 10 lines of glsl shader code, or maybe 10 lines of a language like Haskell might be counted in complexity as the same as 10 lines of BASIC, does that even make sense? can there be a parameter where one can indicate the avg cost for each developer?, I know estimates aren't perfect, but I'd like to know this.

9. how is code that generates other code being estimated for cost? is that more complex?
10. what about self-modifying code?
11. do generics impact the estimate cost? what about things like macros? can configuration files be auto-detected as such?

12. I leave these ideas here in the hopes it would spark an interesting conversation :)

````
localhost:scc-master b$ ~/scc .
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines     Code  Comments   Blanks Complexity
───────────────────────────────────────────────────────────────────────────────
Java                        21      3725     2345       620      760        521
Go                          19      5452     4359       454      639        673
Python                       8       343      306        19       18         29
Markdown                     5       614      498         0      116          0
Powershell                   2       240       46       159       35          8
Plain Text                   2        31       24         0        7          0
License                      2        45       37         0        8          0
ignore                       2         2        2         0        0          0
Report Definition L…         1         0        0         0        0          0
Futhark                      1        29       16        10        3          2
Alloy                        1        50        4        40        6          0
Gherkin Specificati…         1         0        0         0        0          0
gitignore                    1        33       19         7        7          0
JSON                         1      6852     6851         0        1          0
nuspec                       1        22       22         0        0          0
Alchemist                    1        20       20         0        0         55
Wren                         1       188      131        35       22          8
Luna                         1        23       17         1        5          0
Q#                           1        31       23         2        6          5
Bitbucket Pipeline           1        23       22         0        1          0
Macromedia eXtensib…         1         0        0         0        0          0
TOML                         1        38        9        25        4          0
Varnish Configurati…         1         0        0         0        0          0
JavaServer Pages             1         0        0         0        0          0
Extensible Styleshe…         1         0        0         0        0          0
Docker ignore                1         3        2         1        0          0
Flow9                        1        21       12         6        3          5
Bosque                       1       179      139         8       32          1
Freemarker Template          1         0        0         0        0          0
Coq                          1       168      141         9       18          5
SystemVerilog                1        79       51        21        7          5
Monkey C                     1        74       62         0       12         12
YAML                         1        20       19         0        1          0
Shell                        1       294      252         8       34         36
V                            1        73       35        30        8          3
───────────────────────────────────────────────────────────────────────────────
Total                       88     18672    15464      1455     1753       1368
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop $479,052
Estimated Schedule Effort 11.599424 months
Estimated People Required 4.892170
───────────────────────────────────────────────────────────────────────────────

````

**Comment by boyter** [comment]
Woah a lot to process there. Glad you liked it.

1. So this is something I have been toying with https://github.com/boyter/scc/issues/43 however in the case of Angular because its inside HTML templates it can be problematic. 

What would have to happen is that the file would be scanned based on extension, and then if it sees `ng-whatever` or whatever causes it to change logic flip and then reprocess that file. This is not a massive issue but annoying to implement. I am prepared to put the work in, but I would need to understand how each of the template languages work first so that I can make it flexible enough to work with all of them.

In short, yes its possible, but I need help before I start to tackle this one.

2. The cost is based on the COCOMO2 model https://en.wikipedia.org/wiki/COCOMO which actually includes the cost of developing the software totally and not just the programmer cost. This means its supposed to include costs of electricity, the building you are sitting in, requirements gathering, testing etc...

COCOMO is meant to be flexible but in the case of `scc` this seemed like overkill and I implemented it using the following defaults "based on organic project small team, good experience working with requirements"

The numbers can seem high at times. However in the case of `scc` itself its pretty close. The project has existed for just over that many months and while I have done the majority of the work there have been a great many submissions from people like @dbaggerman and others. 

If you can find a better model for estimating cost I will be happy to implement it.

3. This has come up a few times. I may need to link to some good details about COCOMO which explains this.

4. Yes, however it may be better to do so through a `.ignore` file in your repository. This is becoming the standard for files that you want added to your source control but to be ignored by tools such as ripgrep, scc, ag, vs-code and others. You can also do so at runtime `scc --exclude-dir vendor,node_modules` but I would suggest .ignore is the best approach here.

I am not opposed to adding these to the default ignore list but its not something I would want to do without really understanding the impact.

5. Minified code can be detected. I do so in searchcode.com for example where I check the average line length. I have created https://github.com/boyter/scc/issues/92 

6. I belive they are not currently. COCOMO only works for code as far as I am aware. Perhaps something to turn it on? I would want to see some studies working out how you cost for this before implementing though.

7. If you can find an implementation or method for doing son. You can infer this from the complexity estimate I suppose but a formal method might be nice.

8. The complexity estimate is really just a number that is only comparable to files in the same language. It should not be used to compare languages directly without weighting them. The reason for this is that its calculated by looking for branch and loop statements in the code and incrementing a counter for that file.

Because some languages don't have loops and must use recursion they can have a lower complexity count. Does this mean they are less complex? Probably not, but the tool cannot see this.

If you want to do this you can run `scc` multiple times specifying the extension `scc -i java` for example and use those numbers.

Generally though the complexity there is to help estimate between projects written in the same language, or for finding the most complex file in a project `scc --by-file -s complexity` which can be useful when you are estimating on how hard something is to maintain.

I am totally turning the above into a post about how it works, because you are not the first person to ask this.

9. The tool is unaware that some code may generate other code. As such its complexity will totally be down to how many branch/loop conditions are in it. In practice though such code usually has a lot of these conditions and is the most complex when counted.

10. See 9.

11. No. Can macros be counted... not sure. Can you provide an example of how this would work. Config files... can you provide a real example.

12. No worries. Its good for me to walk though how I expect the tool to work vs what peoples perception is.

**Comment by boyter** [comment]
Going to close this as no response in a while. Going to assume everything was answered to satisfaction.

 Random note I am toying with the maintainability index calculation. Would be something that appears in the JSON or wide output.
